### ISSUE TITLE
NLB LoadBalancer doesn't update security groups

### ISSUE THREAD

**Issue by selslack** [kubernetes/cloud-provider-aws#36]
I've changed `loadBalancerSourceRanges` for the `LoadBalancer` service with `service.beta.kubernetes.io/aws-load-balancer-type: nlb` annotation.

**What happened**: Well, nothing.

**What you expected to happen**: SG for node should be updated with corresponding ranges from `loadBalancerSourceRanges`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create `LoadBalancer` service with `service.beta.kubernetes.io/aws-load-balancer-type: nlb` annotation and 1 element in `loadBalancerSourceRanges`.
1. Check SG in the cloud.
1. Add 2nd element to `loadBalancerSourceRanges`.
1. Check SG in the cloud.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:05:06Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from /etc/os-release): AWS EKS
- Kernel (e.g. `uname -a`): AWS EKS
- Install tools:
- Others:

/kind bug

**Comment by ykzj** [comment]
NLB is not supporting security group now.

**Comment by selslack** [comment]
@ykzj This is about Security Groups **for nodes**, which are being applied/managed by k8s to support `loadBalancerSourceRanges`.

**Comment by adamrbennett** [comment]
I'm also facing this. Moreover, I'm getting duplicate rules -- one set of rules for `0.0.0.0/0` and another identical set for my VPC CIDR.

What can I do to help troubleshoot?

**Comment by TiagoJMartins** [comment]
I'm also being affected by this as the NLB needs to be recreated for the changes to take effect.

**Comment by larsrnielsen** [comment]
Facing the same issue. I have also tried to force a recreation of the NLB, but no luck on SG update

**Comment by M00nF1sh** [comment]
@larsrnielsen what's the k8s version used? the original issue should have already been addressed by https://github.com/kubernetes/kubernetes/pull/74692/files

**Comment by nckturner** [comment]
/close

Please reopen this issue if its not fixed by https://github.com/kubernetes/kubernetes/pull/74692

**Comment by pasdam** [comment]
I'm still facing this issue in k8s 1.24

```
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.10-eks-48e63af", GitCommit:"9176fb99b52f8d5ff73d67fea27f3a638f679f8a", GitTreeState:"clean", BuildDate:"2023-01-24T19:17:48Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

We have a loadbalancer service where we set `loadBalancerSourceRanges`, but the updates to this list don't propagate to the SG. Recreating the service is not an option for us, especially in production. Can we reopen this?

/reopen
